/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF("/setup.glb");
    const { actions } = useAnimations(animations, group);
    useEffect(() => {
        actions["Armature|mixamo.com|Layer0"].play();
        props.setLoading(false);
    });
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group
                    name="Wireless_Mouse"
                    position={[-2.72, 2.99, -0.33]}
                    rotation={[0, -1.25, 0]}
                    scale={[4.43, 5.22, 6.47]}
                />
                <group name="Pillow">
                    <mesh
                        name="Cube002"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube002.geometry}
                        material={materials.Cotton}
                        position={[2.97, 1.5, 2.93]}
                        rotation={[-0.43, 0, 0]}
                        scale={[1.3, 0.07, 1.04]}
                    />
                </group>
                <group
                    name="Gaming_Mouse"
                    position={[-2.66, 3, -0.43]}
                    rotation={[-Math.PI, 1.15, -Math.PI]}
                    scale={[9.66, 11.08, 8.98]}
                >
                    <mesh
                        name="MouseThermaltakeBlack"
                        castShadow
                        receiveShadow
                        geometry={nodes.MouseThermaltakeBlack.geometry}
                        material={materials["Material.003"]}
                        position={[0, 0.01, -0.02]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.03, 0.02, 0.02]}
                    />
                    <mesh
                        name="MouseThermaltakeBlack001"
                        castShadow
                        receiveShadow
                        geometry={nodes.MouseThermaltakeBlack001.geometry}
                        material={materials["Material.008"]}
                        position={[-0.01, 0.01, 0.01]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                    />
                    <mesh
                        name="MouseThermaltakeBlack002"
                        castShadow
                        receiveShadow
                        geometry={nodes.MouseThermaltakeBlack002.geometry}
                        material={materials["Material.004"]}
                        position={[-0.02, 0.01, -0.01]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                    />
                    <mesh
                        name="MouseThermaltakeBlack004"
                        castShadow
                        receiveShadow
                        geometry={nodes.MouseThermaltakeBlack004.geometry}
                        material={materials["Material.003"]}
                        position={[0, 0.01, -0.01]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                    />
                    <mesh
                        name="MouseThermaltakeBlack007"
                        castShadow
                        receiveShadow
                        geometry={nodes.MouseThermaltakeBlack007.geometry}
                        material={materials["Material.003"]}
                        position={[0, 0.01, -0.01]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                    />
                    <mesh
                        name="MouseThermaltakeBlack009"
                        castShadow
                        receiveShadow
                        geometry={nodes.MouseThermaltakeBlack009.geometry}
                        material={materials["main body"]}
                        position={[0, 0.01, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                    />
                    <mesh
                        name="MouseThermaltakeBlack010"
                        castShadow
                        receiveShadow
                        geometry={nodes.MouseThermaltakeBlack010.geometry}
                        material={materials["Material.009"]}
                        position={[-0.01, 0.01, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                    />
                    <mesh
                        name="MouseThermaltakeBlack005"
                        castShadow
                        receiveShadow
                        geometry={nodes.MouseThermaltakeBlack005.geometry}
                        material={materials["Material.016"]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                    />
                    <mesh
                        name="MouseThermaltakeBlack011"
                        castShadow
                        receiveShadow
                        geometry={nodes.MouseThermaltakeBlack011.geometry}
                        material={materials["main body"]}
                        position={[0, 0.01, -0.01]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                    />
                    <mesh
                        name="MouseThermaltakeBlack012"
                        castShadow
                        receiveShadow
                        geometry={nodes.MouseThermaltakeBlack012.geometry}
                        material={materials["Material.002"]}
                        position={[0, 0.01, -0.01]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                    />
                    <mesh
                        name="MouseThermaltakeBlack013"
                        castShadow
                        receiveShadow
                        geometry={nodes.MouseThermaltakeBlack013.geometry}
                        material={materials["Material.002"]}
                        position={[0, 0.01, -0.01]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                    />
                    <mesh
                        name="MouseThermaltakeBlack014"
                        castShadow
                        receiveShadow
                        geometry={nodes.MouseThermaltakeBlack014.geometry}
                        material={materials["Material.001"]}
                        position={[0, 0.01, -0.02]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                    />
                    <mesh
                        name="MouseThermaltakeBlack008"
                        castShadow
                        receiveShadow
                        geometry={nodes.MouseThermaltakeBlack008.geometry}
                        material={materials["main body.001"]}
                        position={[0, 0.01, -0.02]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                    />
                    <group
                        name="MouseThermaltakeBlack003"
                        position={[0, 0.01, -0.01]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                    >
                        <mesh
                            name="MouseThermaltakeBlack003_1"
                            castShadow
                            receiveShadow
                            geometry={nodes.MouseThermaltakeBlack003_1.geometry}
                            material={materials["main body"]}
                        />
                        <mesh
                            name="MouseThermaltakeBlack003_2"
                            castShadow
                            receiveShadow
                            geometry={nodes.MouseThermaltakeBlack003_2.geometry}
                            material={materials["Material.007"]}
                        />
                        <mesh
                            name="MouseThermaltakeBlack003_3"
                            castShadow
                            receiveShadow
                            geometry={nodes.MouseThermaltakeBlack003_3.geometry}
                            material={materials["Material.013"]}
                        />
                        <mesh
                            name="MouseThermaltakeBlack003_4"
                            castShadow
                            receiveShadow
                            geometry={nodes.MouseThermaltakeBlack003_4.geometry}
                            material={materials["Material.014"]}
                        />
                    </group>
                    <group
                        name="MouseThermaltakeBlack015"
                        position={[0, 0.01, -0.01]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.02}
                    >
                        <mesh
                            name="MouseThermaltakeBlack015_1"
                            castShadow
                            receiveShadow
                            geometry={nodes.MouseThermaltakeBlack015_1.geometry}
                            material={materials["Material.002"]}
                        />
                        <mesh
                            name="MouseThermaltakeBlack015_2"
                            castShadow
                            receiveShadow
                            geometry={nodes.MouseThermaltakeBlack015_2.geometry}
                            material={materials["Material.010"]}
                        />
                        <mesh
                            name="MouseThermaltakeBlack015_3"
                            castShadow
                            receiveShadow
                            geometry={nodes.MouseThermaltakeBlack015_3.geometry}
                            material={materials["Material.012"]}
                        />
                    </group>
                </group>
                <group
                    name="Armature"
                    position={[-0.16, 0.49, 1.38]}
                    rotation={[1.57, -1.57, 1.57]}
                    scale={3.5}
                >
                    <primitive object={nodes.Hips} />
                    <skinnedMesh frustumCulled={false}
                        name="EyeLeft"
                        geometry={nodes.EyeLeft.geometry}
                        material={materials.Wolf3D_Eye}
                        skeleton={nodes.EyeLeft.skeleton}
                        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
                        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
                    />
                    <skinnedMesh frustumCulled={false}
                        name="EyeRight"
                        geometry={nodes.EyeRight.geometry}
                        material={materials.Wolf3D_Eye}
                        skeleton={nodes.EyeRight.skeleton}
                        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
                        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
                    />
                    <skinnedMesh frustumCulled={false}
                        name="Wolf3D_Hair"
                        geometry={nodes.Wolf3D_Hair.geometry}
                        material={materials.Wolf3D_Hair}
                        skeleton={nodes.Wolf3D_Hair.skeleton}
                    />
                    <skinnedMesh frustumCulled={false}
                        name="Wolf3D_Head"
                        geometry={nodes.Wolf3D_Head.geometry}
                        material={materials.Wolf3D_Skin}
                        skeleton={nodes.Wolf3D_Head.skeleton}
                        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
                        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
                    />
                    <skinnedMesh frustumCulled={false}
                        name="Wolf3D_Teeth"
                        geometry={nodes.Wolf3D_Teeth.geometry}
                        material={materials.Wolf3D_Teeth}
                        skeleton={nodes.Wolf3D_Teeth.skeleton}
                        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
                        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
                    />
                    <skinnedMesh frustumCulled={false}
                        name="Wolf3D_Outfit_Footwear"
                        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
                        material={materials.Wolf3D_Outfit_Footwear}
                        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
                    />
                    <skinnedMesh frustumCulled={false}
                        name="Wolf3D_Outfit_Top"
                        geometry={nodes.Wolf3D_Outfit_Top.geometry}
                        material={materials.Wolf3D_Outfit_Top}
                        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
                    />
                    <skinnedMesh frustumCulled={false}
                        name="Wolf3D_Outfit_Bottom"
                        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
                        material={materials.Wolf3D_Outfit_Bottom}
                        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
                    />
                    <skinnedMesh frustumCulled={false}
                        name="Wolf3D_Body"
                        geometry={nodes.Wolf3D_Body.geometry}
                        material={materials.Wolf3D_Body}
                        skeleton={nodes.Wolf3D_Body.skeleton}
                    />
                </group>
                <mesh
                    name="kamera"
                    castShadow
                    receiveShadow
                    geometry={nodes.kamera.geometry}
                    material={nodes.kamera.material}
                    position={[-3.25, 5.02, -0.84]}
                    rotation={[0, -0.52, 0]}
                    scale={[0.02, 0.07, 0.16]}
                />
                <mesh
                    name="saklar"
                    castShadow
                    receiveShadow
                    geometry={nodes.saklar.geometry}
                    material={materials.saklar}
                    position={[1.94, 4.75, 4.11]}
                    scale={[0.33, 0.2, 0.05]}
                />
                <mesh
                    name="tempat_minum"
                    castShadow
                    receiveShadow
                    geometry={nodes.tempat_minum.geometry}
                    material={materials["tempat minum"]}
                    position={[-3.12, 3.13, -2.17]}
                    scale={[0.98, 0.14, 0.33]}
                />
                <mesh
                    name="tatakan_kamera"
                    castShadow
                    receiveShadow
                    geometry={nodes.tatakan_kamera.geometry}
                    material={nodes.tatakan_kamera.material}
                    position={[-3.34, 4.98, -0.91]}
                    rotation={[0, -0.52, 0]}
                    scale={[0.01, 0.07, 0.15]}
                />
                <mesh
                    name="Plane"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane.geometry}
                    material={materials["Material.022"]}
                    position={[-1.98, 3.77, -3.4]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={[3.19, 1, 0.77]}
                />
                <mesh
                    name="lantai"
                    castShadow
                    receiveShadow
                    geometry={nodes.lantai.geometry}
                    material={materials["Material.011"]}
                    scale={[4.36, 0.11, 4.36]}
                />
                <mesh
                    name="tatakan_laptop"
                    castShadow
                    receiveShadow
                    geometry={nodes.tatakan_laptop.geometry}
                    material={materials["tatakan laptop"]}
                    position={[-4.06, 3.37, 2.16]}
                    scale={[0.03, 0.35, 0.03]}
                />
                <mesh
                    name="tembok_kanan"
                    castShadow
                    receiveShadow
                    geometry={nodes.tembok_kanan.geometry}
                    material={materials["Material.006"]}
                    position={[-4.24, 4.25, -0.01]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                    scale={[4.36, 0.11, 4.36]}
                />
                <mesh
                    name="layar_laptop"
                    castShadow
                    receiveShadow
                    geometry={nodes.layar_laptop.geometry}
                    material={materials["layaar laptop"]}
                    position={[-4.06, 4.34, 1.26]}
                    scale={[0.02, 0.57, 0.99]}
                />
                <mesh
                    name="badan_laptop"
                    castShadow
                    receiveShadow
                    geometry={nodes.badan_laptop.geometry}
                    material={materials["Badan Laptop"]}
                    position={[-3.59, 3.43, 1.25]}
                    rotation={[0, 0, 0.94]}
                    scale={[0.03, 0.61, 0.99]}
                />
                <mesh
                    name="luaran_key_Laptop"
                    castShadow
                    receiveShadow
                    geometry={nodes.luaran_key_Laptop.geometry}
                    material={materials["Luaran keyboard L"]}
                    position={[-3.72, 3.55, 1.26]}
                    rotation={[0, 0, 0.94]}
                    scale={[0.01, 0.35, 0.89]}
                />
                <mesh
                    name="trackpad_laptop"
                    castShadow
                    receiveShadow
                    geometry={nodes.trackpad_laptop.geometry}
                    material={materials["trackpad laptop"]}
                    position={[-3.26, 3.22, 1.26]}
                    rotation={[0, 0, 0.94]}
                    scale={[0.01, 0.2, 0.4]}
                />
                <mesh
                    name="Badan_Keyboard"
                    castShadow
                    receiveShadow
                    geometry={nodes.Badan_Keyboard.geometry}
                    material={materials["Badan Keyboard"]}
                    position={[-2.88, 2.95, 2.1]}
                    rotation={[1.57, 0, -1.57]}
                    scale={[-0.09, -0.03, 0]}
                />
                <mesh
                    name="stop_kontak"
                    castShadow
                    receiveShadow
                    geometry={nodes.stop_kontak.geometry}
                    material={materials["stop kontak"]}
                    position={[-4, 2.61, -0.52]}
                    rotation={[-Math.PI, 0, -Math.PI]}
                    scale={[-0.14, -0.15, -0.65]}
                />
                <mesh
                    name="mousepad"
                    castShadow
                    receiveShadow
                    geometry={nodes.mousepad.geometry}
                    material={materials.mousepad}
                    position={[-2.94, 2.96, 1.23]}
                    scale={[1.06, 0.03, 2.8]}
                />
                <mesh
                    name="button_trackpad_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.button_trackpad_1.geometry}
                    material={materials["button trackpad 1"]}
                    position={[-3.14, 3.12, 1.45]}
                    rotation={[-Math.PI, 0, 2.21]}
                    scale={[0, -0.05, -0.2]}
                />
                <mesh
                    name="button_trackpad_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.button_trackpad_2.geometry}
                    material={materials["button trackpad 2"]}
                    position={[-3.14, 3.12, 1.06]}
                    rotation={[-Math.PI, 0, 2.21]}
                    scale={[0, -0.05, -0.2]}
                />
                <mesh
                    name="Keycaps_Keyboard"
                    castShadow
                    receiveShadow
                    geometry={nodes.Keycaps_Keyboard.geometry}
                    material={materials["Keycaps Keyboard"]}
                    position={[-2.49, 3.08, 1.62]}
                    rotation={[1.57, -0.02, Math.PI / 2]}
                    scale={[0.06, 0.06, 0.04]}
                />
                <mesh
                    name="lampu"
                    castShadow
                    receiveShadow
                    geometry={nodes.lampu.geometry}
                    material={materials.lampu}
                    position={[-3.9, 7.87, -0.07]}
                    scale={[0.27, 0.22, 2.44]}
                />
                <mesh
                    name="lampu_terang"
                    castShadow
                    receiveShadow
                    geometry={nodes.lampu_terang.geometry}
                    material={nodes.lampu_terang.material}
                    position={[-4.01, 7.74, 0.06]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={[0.14, 2.28, 0.14]}
                />
                <mesh
                    name="monitor_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.monitor_2.geometry}
                    material={materials["monitor 2"]}
                    position={[-3.64, 3.39, -0.94]}
                    rotation={[0, -0.2, 0]}
                    scale={[0.06, 0.32, 0.06]}
                />
                <mesh
                    name="tutup_minum"
                    castShadow
                    receiveShadow
                    geometry={nodes.tutup_minum.geometry}
                    material={materials["tutup minum"]}
                    position={[-2.65, 3.76, -2.15]}
                    scale={[0.32, 0.04, 0.32]}
                />
                <mesh
                    name="lampu_terang001"
                    castShadow
                    receiveShadow
                    geometry={nodes.lampu_terang001.geometry}
                    material={nodes.lampu_terang001.material}
                    position={[-4.01, 2.62, 2.1]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={[0.05, 1.98, 0.05]}
                />
                <mesh
                    name="saklar_kiri"
                    castShadow
                    receiveShadow
                    geometry={nodes.saklar_kiri.geometry}
                    material={nodes.saklar_kiri.material}
                    position={[2.07, 4.76, 4.05]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[-0.08, -0.12, -0.02]}
                />
                <mesh
                    name="saklar_kanan"
                    castShadow
                    receiveShadow
                    geometry={nodes.saklar_kanan.geometry}
                    material={nodes.saklar_kanan.material}
                    position={[1.86, 4.76, 4.05]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[-0.08, -0.12, -0.02]}
                />
                <mesh
                    name="Keycaps_Keyboard_L"
                    castShadow
                    receiveShadow
                    geometry={nodes.Keycaps_Keyboard_L.geometry}
                    material={materials["Keycaps Keyboard L"]}
                    position={[-3.68, 3.5, 1.57]}
                    rotation={[1.57, -0.64, 1.57]}
                    scale={[0.05, 0.05, 0.04]}
                />
                <mesh
                    name="monitor_2001"
                    castShadow
                    receiveShadow
                    geometry={nodes.monitor_2001.geometry}
                    material={materials["monitor 2"]}
                    position={[-3.41, 3.39, 3.36]}
                    rotation={[0, 1, 0]}
                    scale={[0.06, 0.32, 0.06]}
                />
                <mesh
                    name="minum_aer"
                    castShadow
                    receiveShadow
                    geometry={nodes.minum_aer.geometry}
                    material={materials["minum aer"]}
                    position={[-2.64, 3.38, -2.15]}
                    scale={[0.27, 0.39, 0.23]}
                />
                <mesh
                    name="blanket"
                    castShadow
                    receiveShadow
                    geometry={nodes.blanket.geometry}
                    material={materials.blanket}
                    position={[2.94, 2.27, 0.17]}
                    scale={[1.87, 1.21, 3.35]}
                />
                <mesh
                    name="poto_41"
                    castShadow
                    receiveShadow
                    geometry={nodes.poto_41.geometry}
                    material={materials["poto 4.1"]}
                    position={[0.21, 5.83, 3.95]}
                    scale={[0.54, 0.63, 0.02]}
                />
                <mesh
                    name="trashcan"
                    castShadow
                    receiveShadow
                    geometry={nodes.trashcan.geometry}
                    material={materials.trashcan}
                    position={[-3.04, 0.94, -0.83]}
                    scale={[0.85, 0.85, 0.36]}
                />
                <mesh
                    name="meja"
                    castShadow
                    receiveShadow
                    geometry={nodes.meja.geometry}
                    material={materials.meja}
                    position={[-2.94, 2.87, 0.83]}
                    scale={[1.21, 0.11, 3.31]}
                />
                <mesh
                    name="lemari_bawah_meja"
                    castShadow
                    receiveShadow
                    geometry={nodes.lemari_bawah_meja.geometry}
                    material={materials["lemari bawah meja"]}
                    position={[-3.12, 1.44, -1.82]}
                    scale={[1.02, 1.34, 0.65]}
                />
                <mesh
                    name="pintu_lemari_bawah"
                    castShadow
                    receiveShadow
                    geometry={nodes.pintu_lemari_bawah.geometry}
                    material={materials["Pintu lemari bawah"]}
                    position={[-2.07, 1.43, -1.81]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[-0.05, -1.33, -0.64]}
                />
                <mesh
                    name="poto_31"
                    castShadow
                    receiveShadow
                    geometry={nodes.poto_31.geometry}
                    material={materials["poto 3.1"]}
                    position={[-1.02, 5.83, 3.98]}
                    scale={[0.55, 0.64, 0.02]}
                />
                <mesh
                    name="kasur"
                    castShadow
                    receiveShadow
                    geometry={nodes.kasur.geometry}
                    material={materials.kasur}
                    position={[2.94, 0.86, 0.33]}
                    scale={[1.31, 0.22, 3.52]}
                />
                <group
                    name="Office_chair"
                    position={[-0.45, 0.23, 1.38]}
                    rotation={[-Math.PI, 1.54, -Math.PI]}
                    scale={[3.7, 3.89, 2.93]}
                >
                    <mesh
                        name="Plane002"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane002.geometry}
                        material={materials["chrome metal"]}
                    />
                    <mesh
                        name="Plane002_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane002_1.geometry}
                        material={materials["plastic black rough"]}
                    />
                    <mesh
                        name="Plane002_2"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane002_2.geometry}
                        material={materials.fabric}
                    />
                    <mesh
                        name="Plane002_3"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane002_3.geometry}
                        material={materials["metal painted"]}
                    />
                    <mesh
                        name="Plane002_4"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane002_4.geometry}
                        material={materials["plastic smooth"]}
                    />
                </group>
                <mesh
                    name="pintu_lemari"
                    castShadow
                    receiveShadow
                    geometry={nodes.pintu_lemari.geometry}
                    material={materials["pintu lemari"]}
                    position={[-2.08, 3.59, -3.39]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[-0.07, -3.5, -0.91]}
                />
                <mesh
                    name="1"
                    castShadow
                    receiveShadow
                    geometry={nodes["1"].geometry}
                    material={materials["poto 1"]}
                    position={[-0.42, 7.33, 4.18]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={[1.21, 0.11, 0.79]}
                />
                <mesh
                    name="kayu_kasur"
                    castShadow
                    receiveShadow
                    geometry={nodes.kayu_kasur.geometry}
                    material={materials["kayu kasur"]}
                    position={[2.92, 0.37, 0.46]}
                    scale={[1.43, 0.28, 3.76]}
                />
                <mesh
                    name="board"
                    castShadow
                    receiveShadow
                    geometry={nodes.board.geometry}
                    material={materials.board}
                    position={[-3.09, 5.08, -2.42]}
                    rotation={[0, 0, -Math.PI]}
                    scale={[-0.82, -1.06, -0.06]}
                />
                <mesh
                    name="lemari_atas_kasur"
                    castShadow
                    receiveShadow
                    geometry={nodes.lemari_atas_kasur.geometry}
                    material={materials["leamri atas kasur"]}
                    position={[2.92, 3.62, 4.2]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={[1.4, 0.15, 0.79]}
                />
                <mesh
                    name="poto_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.poto_2.geometry}
                    material={materials["poto 2"]}
                    position={[-2.47, 6.62, 4.18]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                    scale={[1.52, 0.11, 0.79]}
                />
                <mesh
                    name="poto_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.poto_3.geometry}
                    material={materials["poto 3"]}
                    position={[-1.01, 5.82, 4.18]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={[0.6, 0.11, 0.72]}
                />
                <mesh
                    name="poto_4"
                    castShadow
                    receiveShadow
                    geometry={nodes.poto_4.geometry}
                    material={materials["poto 4"]}
                    position={[0.2, 5.82, 4.18]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={[0.6, 0.11, 0.72]}
                />
                <mesh
                    name="poto_21"
                    castShadow
                    receiveShadow
                    geometry={nodes.poto_21.geometry}
                    material={materials["poto 2.1"]}
                    position={[-2.47, 6.62, 4.07]}
                    scale={[0.71, 1.42, 0.04]}
                />
                <mesh
                    name="layar_monitor_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.layar_monitor_2.geometry}
                    material={materials["layar monitor 2"]}
                    position={[-3.33, 4.33, -0.76]}
                    rotation={[0, -0.5, 0]}
                    scale={[0.02, 0.63, 1.04]}
                />
                <mesh
                    name="layar_monitor_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.layar_monitor_1.geometry}
                    material={materials["layar monitor 1"]}
                    position={[-3.15, 4.33, 3.13]}
                    rotation={[0, 0.7, 0]}
                    scale={[0.02, 0.63, 1.04]}
                />
                <mesh
                    name="layar_monitor_laptop"
                    castShadow
                    receiveShadow
                    geometry={nodes.layar_monitor_laptop.geometry}
                    material={materials["layar monitor laptop"]}
                    position={[-4.05, 4.37, 1.25]}
                    scale={[0.02, 0.49, 0.96]}
                />
                <mesh
                    name="poster"
                    castShadow
                    receiveShadow
                    geometry={nodes.poster.geometry}
                    material={materials.poster}
                    position={[3.05, 6.65, 4.11]}
                    scale={[1, 1.49, 0.06]}
                />
                <mesh
                    name="poto_11"
                    castShadow
                    receiveShadow
                    geometry={nodes.poto_11.geometry}
                    material={materials["poto 1.1"]}
                    position={[-0.42, 7.32, 3.97]}
                    scale={[1.13, 0.71, 0.04]}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/setup.glb");


